name: CI

on   : push
   

jobs :
   linting:
       runs-on: ubuntu-latest
        
       steps:
        -name: code checkout
        uses: actions/checkout@v3
        -name: setup python
        uses: actions/setup-python@v2
        with:
          python versions: ${{matrix.versions}}
        -name: install flake8
        run: |
            python -m pip install --upgrade pip  
            pip install flake8
        -name: run flake8
        run: |
            flake8 app.py
   testing:
       needs: linting
       runs-on: ${{matrix.os}}
        
       stratergy:
          matrix:
            os: ['ubuntu-latest','windows-latest','macos-latest']
            versions: ['3.9','3.10','3.11']

       steps:
        -name: code checkout
        uses: actions/checkout@v3
        -name: setup python
        uses: actions/setup-python@v2
        with:
          python versions: ${{matrix.versions}}
        -name: Cache pip dependacies 
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
        -name: install dependacies
        run: |
            pip install -r requirements.txt
        -name: run dvc pipeline
        run: |
            dvc repro
        -name: run model tests
        run: |
            python -m unittest tests/test_model.py
        -name: promote model to production
        if: success()
        run: |
            python scripts/promote_model.py
        -name: run flask app tests
        if: success()
        run: |
            python -m unittest tests/test_flask.py
        
        

