stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/features/data_preprocessing.py
    deps:
    - data/raw/reddit_train.csv
    - data/raw/reddit_test.csv
    - src/features/data_preprocessing.py
    outs:
    - data/interim
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/interim/reddit_train.csv
    - data/interim/reddit_test.csv
    - src/features/feature_engineering.py
    params:
    - feature_engineering.n_gram
    - feature_engineering.max_features
    outs:
    - data/processed
    - vectorizer.pkl
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/interim/reddit_train.csv
    - src/model/model_building.py
    params:
    - model_building.n_estimators
    - model_building.learning_rate
    - model_building.max_depth
    outs:
    - best_model.pkl
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - best_model.pkl
    - vectorizer.pkl
    - data/processed/reddit_test.csv
    - src/model/model_building.py
   
